grasp_node:
  ros__parameters:
    menu_mode: false # Left this to false, it will be set to true when the menu is activated (grasp_bag.cpp)
    sim_mode: true
    base_frame: "base_link"
    camera_frame: "camera_link"
    orientation_tolerance: 0.01
    home_pose: [0. , -90. , 90. , -90. , -90. , -90.] # [0. , -90. , -90. , -90. , 90. , -90. ]
    scan_pose: [0., -95., 140., -200., -90., -90.]  # [0., -95., -140., 30., 90., -90.] , [0., -95., -120., -80., 90., -90.]
    # -> morbida (0., -60., 120., -60., 90., 180.)
    # -> media (0., -80., 140., -60., 90., 180.)
    # -> spigolosa (0., -80., 160., -80., 90., 180.)
    grasping_pose: [0. , -60. , 60. , -90. , -90. , -90.] # Position over the bag
    neobotix_mpo_500: false # True if omnidirectional robot neobotix mpo-500 is used
    box_down_pose: [-0.25, 0.0, -0.25, 0.0, 0.0, 0.0, 1.0] # pose box_down
    box_down_size: [1.0, 0.7, 0.5] # size box_down
    box_up_pose: [-0.5, 0.0, 0.2, 0.0, 0.0, 0.0, 1.0] # pose box_up
    box_down_size: [0.5, 0.7, 0.4] # size box_up


